### PR TITLE
Added URL for the hot fudge quote

### PR DESCRIPTION
**Pull request by oylenshpeegul**
Is it too long now? Should it be long-text?

### CODE REVIEW

**Comment by oylenshpeegul** [comment]
I changed the quotes.edn file, but was unable to regenerate generated.md

```
$ lein run
No :main namespace specified in project.clj.
```

**Comment by Azel4231** [comment]
Thanks for finding the original talk! =)
I think :text is ok, :longtext is more for context information and can be safely ignored.
Would you mind making this change on the latest master commit? It has newlines for every quote in quotes.edn. Moreover the lein problem should be fixed. 
Thanks again!

**Comment by oylenshpeegul** [comment]
Okay, the 'lein run' worked, so I think the generated.md is right now.

I loved that hot fudge quote too...that's why I remembered the talk!

**Comment by oylenshpeegul** [comment]
Oh, I see. Let me start over with Azel4231:master

**Pull request closed without merging**
